AppAcu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# bisa from .views import nama function

urlpatterns = [
    path('', views.content, name='content'),
    path('story1/', views.home, name='home'),
    path('gallery/', views.gallery, name='gallery'),
    path('schedule/', views.formSchedule),
    path('schedule/isi/', views.isischedule),
    path('schedule/isi/<int:id>', views.deleteSchedule, name='deleteSchedule'),
    path('schedule/detail/<int:id>', views.detailSchedule, name='detailSchedule')
]

Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppAcu.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('activity/', views.add_activity, name='activity'),
    path('activity/content/', views.show_activity, name='showactivity'),
    path('activity/registration/<int:activity_id>/', views.registration, name='registration'),
]

story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
	activity = models.CharField(blank=False, max_length=100)
	desc_activity = models.TextField(blank=False)

class Registrant(models.Model):
	name = models.CharField(max_length=100)
	chosen_activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

story6/forms.py
from django import forms
from .models import Activity, Registrant

class FormActivity(forms.Form):

	activity_name_attrs = {
		'class' : 'form-control',
		'type' : 'text',
		'required' : True,
		'placeholder' : 'ex: Swimming'
	}

	activity_desc_attrs = {
		'class' : 'form-control',
		'type' : 'text',
		'required' : True,
		'placeholder' : 'Description of the activity'
	}


	activity = forms.CharField(label = "Name of Activity", max_length=100, widget=forms.TextInput(attrs=activity_name_attrs))
	desc_activity = forms.CharField(label = 'Activity Description', widget=forms.TextInput(attrs=activity_desc_attrs))


class FormRegistrant(forms.Form):

	registrant_attrs = {
		'class' : 'form-control',
		'type' : 'text',
		'required' : True,
		'placeholder' : 'ex: Zalfa Luqyana'
	}

	name = forms.CharField(label = "Name", max_length=100, widget=forms.TextInput(attrs=registrant_attrs))

story6/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import FormActivity, FormRegistrant
from .models import Activity, Registrant
# Create your views here.
def add_activity(request):
	if request.method=='POST':
		form = FormActivity(request.POST)
		if form.is_valid():
			data = Activity()
			data.activity = form.cleaned_data['activity']
			data.desc_activity = form.cleaned_data['desc_activity']
			data.save()
			return redirect('/activity/content')
	form = FormActivity()
	return render(request, 'add_activity.html', {'form' : form})

def show_activity(request):
	activity = Activity.objects.all()
	registrant = Registrant.objects.all()
	response = {
	'activity':activity,
	'registrant':registrant
	}
	return render(request, 'activity_content.html', response)

def registration(request, activity_id):
	if request.method=='POST':
		form = FormRegistrant(request.POST)
		if form.is_valid():
			data = Registrant()
			data.name = form.cleaned_data['name']
			data.chosen_activity = Activity.objects.get(id=activity_id)
			data.save()
			return redirect('/activity/content')
	form = FormRegistrant()
	return render(request, 'registration.html', {'form' : form})

story6/templates/activity_content.html
{% extends 'story3.html' %}
{% load static %}

{% block title %}
<title>List of Activities</title>
{% endblock title %}

{% block content %}
{% if activity %}
<div class="container">
    <h5 class="gal" id="int">Activities</h5>
</div>

<div class="row gallery">
{% for isi in activity %}
<div class="col-md-4 card">
  <div class="card-body act">
    <h5 class="card-title act">{{isi.activity}}</h5>
    <p class="card-text act">{{isi.desc_activity}}</p>
  <ul class="list-group list-group-flush">
    {% if isi.registrant_set.all.count != 0 %}
    <li class="list-group-item"><b>Participant:</b></li>
    {% endif %}
    {% for person in registrant %}
    {% if person.chosen_activity == isi %}
    <li class="list-group-item">{{person.name}}</li>
    {% endif %}
    {% endfor %}
  </ul>
  <div class="card-body">
      {% if request.user.is_authenticated %}
      <a href="{% url 'registration' activity_id=isi.pk %}">
      {% else %}
      <a href="/login">
      {% endif %}
    <button type="button" class="btn btn-outline-danger act">Register</button></a>
  </div>
  </div>
</div>
{% endfor %}
</div>
{% if request.user.is_authenticated %}
<a href="/activity">
{% else %}
<a href="/login">
{% endif %}
<button type="button" class="btn sched"><b>Add New Activity</b></button></a>
{% else %}
<div class='container nodata'>
  <p id='notyet'>no activity has been added, yet</p>
  {% if request.user.is_authenticated %}
  <a href="/activity">
  {% else %}
  <a href="/login">
  {% endif %}
  <button type="button" class="btn sched"><b>Add New Activity</b></button></a>
</div>
{% endif %}
{% endblock %}

story6/templates/add_activity.html
{% extends 'story3.html' %}
{% load static %}

{% block title %}
<title>Add Activity</title>
{% endblock title %}

{% block content %}
<div class="container">
    <h5 class="gal" id="int">Add Activity</h5>
</div>

<div class="form-schedule container schedule row">
	<form method='POST'> {% csrf_token %}
		{{ form }}
		<input type = 'submit' class="button" value='Add Activity' />
	</form>
</div>
{% endblock %}

story6/templates/registration.html
{% extends 'story3.html' %}
{% load static %}

{% block title %}
<title>Registration</title>
{% endblock title %}

{% block content %}
<div class="container">
    <h5 class="gal" id="int">Registration</h5>
</div>

<div class="form-schedule container schedule row">
	<form method='POST'> {% csrf_token %}
		{{ form }}
		<input type = 'submit' class="btn schedule" value='Register' />
	</form>
</div>
{% endblock %}